### ISSUE TITLE
Home page cards should scroll but auto lock on a single card

### ISSUE THREAD

**Issue by tannerhearne** [goinverse-oss/app#120]
## Scope
Home page cards should scroll but auto lock on a single card

<img src="https://user-images.githubusercontent.com/761052/53462418-4c41ad00-3a09-11e9-9c8c-3707200f298b.jpg" height="500" />

## Motion Example
From the Musicbed app.
<img src="https://user-images.githubusercontent.com/761052/53462961-26b5a300-3a0b-11e9-843e-bcad0b7d34a4.gif" height="500" />

## Environment
- Platform (iOS/Android): iOS
- Platform OS version: 12.1.4
- Device: iPhone XS Max

**Comment by brettdh** [comment]
Breadcrumb: react-native makes this really simple.

https://facebook.github.io/react-native/docs/scrollview#snaptoalignment
