### ISSUE TITLE
Remove comment section on single content page and add "Community" screen

### ISSUE THREAD

**Issue by tannerhearne** [goinverse-oss/app#127]
## Scope
Redesign comment section on single content page.

<img src="https://user-images.githubusercontent.com/761052/53463560-d7707200-3a0c-11e9-91ba-1b3036d310b6.jpg" height="500" />

## Environment
- Platform (iOS/Android): iOS
- Platform OS version: 12.1.4
- Device: iPhone XS Max

**Comment by brettdh** [comment]
We decided (in slack) to just remove this section and have a "Community" screen linked from the sidebar menu instead. I'm picking up this issue, and I'll close it when the Community screen is implemented.

If we decide to something else with this section on the media item screen, we can open a new issue for that.
