### ISSUE TITLE
Choose a react-native icon approach

### ISSUE THREAD

**Issue by brettdh** [goinverse-oss/app#29]
Looking briefly at react-native svg support: 
1. It relies on a third-party RN library. 
2. The most popular is [react-native-svg], which is really just a way to use svg as react-native components (as you would in an html document).
3. Other libraries build a nicer abstraction on top of react-native-svg, such as:
  - [react-native-svg-icon]
    - Wrap your svg data in json
    - Refer to icons by name (like an icon font)
  - [react-native-svg-uri]
    - Load content from .svg file (local/remote)
    - ...but Android support has [issues](https://github.com/vault-development/react-native-svg-uri#known-bugs)
  - [react-native-svg-image]
    - Claims to be simpler than above packages with fewer problems
    - Doesn't work with local images; only remote
4. All of the above seem concerningly tied to specific versions of react-native and react-native-svg
  - This could make upgrades tricky in the future

Because of all this, I'm leaning towards the very popular and seemingly-active [react-native-vector-icons] project. It has a bunch of common icon fonts built in, and supports adding our own. It's not as clean to replace our custom icons - have to rebuild the font file rather than replacing a single .svg file - but overall it seems like the approach least likely to cause us major headaches.

I'm open to your suggestions, though, particularly since part of the app building is quite new to me.

[react-native-svg]: https://github.com/react-native-community/react-native-svg
[react-native-svg-icon]: https://github.com/stowball/react-native-svg-icon
[react-native-svg-uri]: https://github.com/vault-development/react-native-svg-uri
[react-native-svg-image]: https://github.com/chitezh/react-native-svg-image
[react-native-vector-icons]: https://github.com/oblador/react-native-vector-icons

**Comment by tannerhearne** [comment]
@brettdh - so are you saying that you don't expect the SVG libraries to update as React Native updates?  So they are locked into a lower version and are not going to come up to the most recent version?

**Comment by brettdh** [comment]
I think they'll get updated, and it's a pretty minor issue since we pin a version of react-native that works with our chosen set of libraries. It's only a (minor) issue when we decide to update react-native - and we're going to have that kind of issue anyway with any library with its own native code/dependencies. It just makes me lean towards the libraries that seem to be more actively maintained, and react-native-vector-icons is the clear standout among these.

**Comment by brettdh** [comment]
That said - @tannerhearne, does it seem ok to maintain our custom icons as an icon font going forward, rather than individual .svg files? And if so, would you be able to document the icons you've used somehow - perhaps in InVision itself, with the name of the icon font and each individual icon?

I leave it to you to decide how best to do that part, since you're far more familiar with the tools. :)

**Comment by tannerhearne** [comment]
@brettdh - It would be a lot easier to use SVGs.  I've used icon fonts in the past and they have unique problems.  Exporting SVGs and having people use them has been the easiest solution for us at Musicbed.  It seems like it is a minor issue, so I would say let's stick with SVG.  Thoughts?

**Comment by brettdh** [comment]
I'm happy to defer to your experience there, since I'm just speculating.

The main issue I see is that it makes development harder - specifically, it makes it harder to add a new icon to the app. At a glance, the most reliable approach seems to be to use react-native-svg-uri but supply the svg as json, as suggested in [this comment](https://github.com/react-native-community/react-native-svg/issues/109#issuecomment-326615624).

I'm assuming that you mean it's harder on the design side to build icon fonts than to export svgs? Or do you mean they're harder to use in development? If you mean the former, maybe the next thing to do then would be for me to look into scripting the conversion from SVG to JSON as suggested in the comment above, and then hook it into our webpack build such that devs just need to drop an .svg file in a directory, and then through a well-documented process, the image is made available as a generated react-native component. Or do you have a more specific react-native recommendation on the dev side that you're using at Musicbed?

Personally, just from this research, I would greatly prefer to use react-native-vector-icons - but I'm not familiar with the problems with icon fonts that you're alluding to, so maybe I'd feel differently if I was more familiar. ¯\\\_(ツ)\_/¯

**Comment by brettdh** [comment]
Also, react-native-svg-uri being  most recently "tested with RN 0.33 and react-native-svg 4.3.1" (we're on RN 0.49) doesn't inspire confidence.

**Comment by tannerhearne** [comment]
@brettdh - Just talked with a colleague and they recommend react-native-vector-icons.  Let's roll with that.

**Comment by brettdh** [comment]
Ace, thanks for investigating.

So, the remaining things to be done here are:
- Create an icon font for the icons that you've created
- Document all icons used, as (icon font, icon name) pairs

Is that something you can take care of? I'm not sure the best place for it to live, though close to the designs is probably best.

**Comment by brettdh** [comment]
Oh, and in the meantime, I'll get the library set up and start with some guesses about which icons the designs used, with some big TODO notes to confirm/correct. :)

**Comment by brettdh** [comment]
Closing as we've reached a decision, and we're tracking further work in #30 and #31.
