### ISSUE TITLE
Set up podcasts state in Redux

### ISSUE THREAD

**Issue by brettdh** [goinverse-oss/app#67]
*Note: the first iteration of redux state (for meditations) has landed as of #82. That initial architecture should be kept in mind as work on this story continues.*

## Motivation
This will be the first non-trivial foray into populating the redux store with app state. It will be an opportunity to prove out and refine our Redux style guide.

We want to store all the state required to display all the screens from the [top-level Podcasts screen] on down. However, we don't want to store more state than is needed, which comes up in this context because there are relations between resources. For instance, a podcast has episodes, and episodes have contributors, but episodes and contributors are standalone entities that we will want to be able to look up outside the context of their related objects. The key is that our state design should allow this without creating duplication. This is referred to in the Redux docs as [*normalizing* the state shape], and the Podcasts project is our first opportunity to try this out.

Chasing breadcrumbs from the redux docs: we should also consider using [redux-orm] to simplify some of the state management of this relational data. (See also the [redux-orm entry] in Mark Erikson's [Practical Redux] series.) If we decide not to (for instance, perhaps because it's overcomplicated and we're not sure if it will fit all use cases), we should definitely still consider using [ImmutableJS] to avoid accidental state mutation in reducers.

[top-level Podcasts screen]: https://github.com/theliturgists/app/issues/62
[*normalizing* the state shape]: https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape
[redux-orm]: https://github.com/tommikaikkonen/redux-orm
[ImmutableJS]: https://facebook.github.io/immutable-js/
[redux-orm entry]: http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/#why-use-redux-orm
[Practical Redux]: http://blog.isquaredsoftware.com/2016/10/practical-redux-part-0-introduction/

## Plan of action
- [x]  Decide on an initial approach and support libraries
  - Doesn't need to be a thorough evaluation; lean towards just trying out something that might work
- [ ] Add actions, reducers, and selectors for podcast state
- [ ] Add tests for all of the above

## Scope
API requests and associated epics (redux-observable) are not part of this story; just the synchronous actions, such as `fetchPodcast` or `fetchPodcastSuccess`, etc.

**Comment by ericbendall** [comment]
Gonna take a stab at this, but first need to refresh myself on redux - reducers and how to organise large-scale app state with it.

**Comment by brettdh** [comment]
@ericbendall just a little poke to un-assign yourself if you decide to actively work on something else :)
