### ISSUE TITLE
Deploy PR commits to Expo for easy review

### ISSUE THREAD

**Issue by brettdh** [goinverse-oss/app#69]
## Motivation
It would be great for reviewers to be able to use Expo on their device to scan a QR code on a PR and instantly be able to play around with the proposed changes. A good example of this in action is react-navigation ([example PR](https://github.com/react-navigation/react-navigation/pull/3708)), which has a [custom webhook](https://github.com/react-navigation/ci-webhook) (running in [now.sh](https://zeit.co/now)) that deploys their playground app to Expo.

However, this ought to be simpler if we just post to the PR from CircleCI itself.

## Plan of action
For both the main app and the storybook:
- [x] Configure a CI job that [publishes to Expo](https://docs.expo.io/versions/latest/guides/publishing.html) with a commit-based release channel
- [x] Make the CI job post a comment to the PR if there is one

## Scope
Eventually we'd also like to deploy production from `master`, but that's not part of this issue.

**Comment by tannerhearne** [comment]
I love this idea @brettdh - using Expo was the way we did demos for our Film + Music Conference app ([on the App Store](https://itunes.apple.com/us/app/film-music-conference/id1280555072?mt=8))

It made it really easy to do tests and provide reviews and feedback without setting up beta users in Buddy Build, Test Flight, etc.
