### ISSUE TITLE
Should accounts be required to use the app?

### ISSUE THREAD

**Issue by brettdh** [goinverse-oss/app#8]
*Note: I moved the details here to [the project] ("User Accounts") and repurposed this issue for discussing whether user accounts should be mandatory.*

*Also: there was some mention (in a previous edit) of other usage data collection beyond the email address, which @wittjosiah pushed back on a bit in the comments below. I've clarified the scope of this in [the project], and in that view, I think it's a minor concern right now, but we should definitely keep it in mind to intentionally be user-minded, including developing a privacy policy.*

[the project]: https://github.com/theliturgists/app/projects

----

Currently, outside this app, people can listen to the main Liturgists podcast (and some meditations that appear on that feed) without giving out any personal info. Should the app be the same way?

Pros of requiring an account:
- Allows us to grab email addresses

Cons of requiring an account:
- Users cannot try the app out to see if they like it
  - I mean this independent of the content; just how the app works and feels
- Users new to The Liturgists might balk and not get involved
  - See recent example with [Our Bible App](https://twitter.com/ourbibleapp/status/957301048305242113)

Personally, I'm in favor of making the app at least somewhat usable without an account, but also giving the user lots of subtle prods to create an account. I actually think this lets us give *more* reasons for a user to create an account, since they'll see the huge amount of content that they could access if they had an account instead of just a couple samples in the intro.

I've got more thoughts here, but they'll have to wait until I have another moment to write 'em out. :)

**Comment by wittjosiah** [comment]
> Users should be required to create an account to use the app

Personally I don't think someone should be forced to create an account. There will be free content and if they only want to listen to that free content I don't think they should necessarily need an account.

> we can store personalized data that they naturally create while using the app

If this is going to be done I think it needs to be clearly indicated to the user that it is being done and why. Ideally I'd say it should be optional and **opt-in**.

**Comment by brettdh** [comment]
@tannerhearne could you chime in on the above? I recall discussing it on a call with you - that it would be simplest to not distinguish between patrons and non-patrons with respect to needing an account for the app - but now I'm having second thoughts. We could still push users to create an account if they want to comment or like something...

**Comment by tannerhearne** [comment]
Hey @wittjosiah - we are requiring the user to create an account to listen to free content so that we can grab their email address.  That’s helpful for marketing reasons because it gives us a touch point to communicate instead of just having anonymous users.  That is also why we provide samples in the walkthrough so users can get an idea of the content before they are required to create a free account.

**Comment by wittjosiah** [comment]
@tannerhearne I realize that this is all pretty standard stuff today for creating apps and services. Personally, I'm just not a fan of a lot of these practices and find them a little discouraging.

> we are requiring the user to create an account to listen to free content so that we can grab their email address

I realize that The Liturgists are creating all this amazing free content, but if you make someone give you their email address for access, its not actually free anymore.

> That’s helpful for marketing reasons because it gives us a touch point to communicate instead of just having anonymous users

I'm not arguing that having information on and ways to contact your users is inherently bad. However, I don't like the practice of forcing users to make an account and submit to handing over usage data. This is definitely debatable, but I would argue that the usage data actually belongs to the user and they are granting you the right to use it. Generally this over-arching right is granted in the EULA and its an all or nothing sort of deal, which is very anti-user.

I think you can foster trust with your users by:
1. Having data collection be opt-in
1. Tell users exactly what data would be collected
1. Tell users what this data would be used for

Following this approach, I suspect that most Liturgists would opt-in to support the team anyways, but it would give the users some of their rights back and also allow vulnerable people to potentially protect themselves. (Perhaps this scenario is a bit over the top, but I know there are people who listen to The Liturgists content and could not imagine what would happen if some people in their community found out. If the app server with user data were to be compromised and the data of Liturgists leaked that could be potentially quite harmful to some people.)

In general, I would push for just being more transparent, even if accounts and data collection is required.

**Comment by brettdh** [comment]
@tannerhearne FWIW, Our Bible App launched recently and it seems they received immediate, widespread feedback against mandatory user accounts. They’re relaxing this in their next version. 

https://twitter.com/ourbibleapp/status/957301048305242113

**Comment by brettdh** [comment]
Overcast just moved in the direction of anonymous accounts: https://marco.org/2018/04/27/overcast42

**Comment by brettdh** [comment]
At this point I think I'm in favor of not requiring an account until a user wants to comment on something.

I go back and forth on whether an account should require an email or just use anonymous credentials stored in the user's iCloud/Google storage - but I strongly lean towards requiring an email for an account, if only for account recovery purposes. (People may change platforms or otherwise lose access to that storage, but their email is pretty stable)

We could still periodically prompt users to sign up for the mailing list, though. It's also easier to articulate and understand a privacy policy in that context, rather than the up-front context of "we might need it for... things... at some point". GDPR has things to say about "email consent" as well: https://litmus.com/blog/5-things-you-must-know-about-email-consent-under-gdpr

**Comment by brettdh** [comment]
In a Slack discussion, @tannerhearne and I agreed that we don't need user accounts for the time being, because we are not implementing comments in the initial version of the app, instead providing links to external discussion forums such as Slack. If this changes in the future, we can revisit this discussion.
